### ISSUE TITLE
openpilot compile on ubuntu20.04.5(nxp board)

### ISSUE THREAD

**Issue by liuhubing** [WeiJiLab/openpilot#4]

**Comment by liuhubing** [comment]
Error with package:
ocl-icd-opencl-dev \
    qml-module-qtquick2 \
    qtmultimedia5-dev \
    qtlocation5-dev \
    qtpositioning5-dev \
    qttools5-dev-tools \
    libqt5sql5-sqlite \
    libqt5svg5-dev \
    libqt5charts5-dev \
    libqt5x11extras5-dev \

**Comment by liuhubing** [comment]
Error info:
/usr/bin/ld: libweston/backend-fbdev/0b62800@@fbdev-backend@sha/fbdev.c.o: in function `fbdev_output_enable':
/root/weston-imx/build/../libweston/backend-fbdev/fbdev.c:628: undefined reference to `fbCreateWindow'
/usr/bin/ld: libweston/backend-fbdev/0b62800@@fbdev-backend@sha/fbdev.c.o: in function `fbdev_output_disable':
/root/weston-imx/build/../libweston/backend-fbdev/fbdev.c:681: undefined reference to `fbDestroyWindow'
/usr/bin/ld: /root/weston-imx/build/../libweston/backend-fbdev/fbdev.c:685: undefined reference to `fbDestroyDisplay'
/usr/bin/ld: libweston/backend-fbdev/0b62800@@fbdev-backend@sha/fbdev.c.o: in function `fbdev_backend_create':
/root/weston-imx/build/../libweston/backend-fbdev/fbdev.c:1140: undefined reference to `fbGetDisplayByIndex'
collect2: error: ld returned 1 exit status

**Comment by liuhubing** [comment]
main base error lib:
libegl-mesa0 libegl1
other base ok:
libglvnd0 libdrm-common libglapi-mesa libwayland-client0 libwayland-server0 libxcb-dri3-0 libxcb-present0 libxcb-sync1

**Comment by liuhubing** [comment]
I found something new today, commaai build their own ubuntu rootfs on https://github.com/commaai/agnos-builder. 
But it also have many library similar with our library before.
